Hermes Modular Refactor
space-concordia-spacecraft/hermes-gsw pull request #1
Opened 2022-02-02 00:39 UTC by AdmiralAki99

PR for Refactor

2022-02-02 18:42 UTC, redknight990 requested changes
Nice job, good solution! Just some minor formatting issues to address. I pushed the project code style configuration, so most formatting issues can be fixed just by running the file formatter in CLion `Ctrl + Alt + L` or `Right-Click on the File => Reformat Code`. Other than that I would separate the base Window class (and any of its new derivates) in its own file so we have less code conflicts if multiple people work on various parts of the UI.

2022-02-02 18:42 UTC, redknight990 commented on .gitignore
> +# .idea/m_Modules.xml
remove this, maybe renamed by accident

2022-02-02 18:42 UTC, redknight990 commented on .gitignore
> +# .idea/m_Modules
remove this, maybe renamed by accident

2022-02-02 18:42 UTC, redknight990 commented on src/Hermes.cpp
> +                if(ImGui::MenuItem("ADCS", NULL)){
```suggestion
                if (ImGui::MenuItem("ADCS", NULL)){
```

2022-02-02 18:42 UTC, redknight990 commented on src/Hermes.cpp
> +                if(ImGui::MenuItem("Comms", NULL)){
```suggestion
                if (ImGui::MenuItem("Comms", NULL)){
```

2022-02-02 18:42 UTC, redknight990 commented on src/Hermes.cpp
> +int Hermes::run(){
```suggestion
int Hermes::Run(){
```

2022-02-02 18:42 UTC, redknight990 commented on src/Hermes.cpp
> +
```suggestion
```

2022-02-02 18:42 UTC, redknight990 commented on src/Hermes.cpp
> +
```suggestion
```

2022-02-02 18:42 UTC, redknight990 commented on src/Hermes.h
> +    int run();
```suggestion
    int Run();
```

2022-02-02 18:42 UTC, redknight990 commented on src/Modules.h
> +    virtual void RenderGUI()=0;
```suggestion
    virtual void RenderGUI() = 0;
```

2022-02-02 18:42 UTC, redknight990 commented on src/Modules.h
> +    virtual GroundStationWindow* GetPtr()=0;
```suggestion
    virtual GroundStationWindow* GetPtr() = 0;
```
Not sure this method is necessary, you can just cast the derived pointer directly

2022-02-02 18:42 UTC, redknight990 commented on src/Modules.h
> +    const string m_WindowName;
Perhaps this name could be returned in a virtual method `GetName`

2022-02-02 18:42 UTC, redknight990 commented on src/Modules.h
> +        m_WindowName=" ";
Use the initializer list here

2022-02-02 18:42 UTC, redknight990 commented on src/Hermes.h
> +    void addWindow(GroundStationWindow* window);
```suggestion
    void AddWindow(GroundStationWindow* window);
```

2022-02-02 18:42 UTC, redknight990 commented on src/Hermes.h
> +private:
Put private members at the end of the class definition

2022-02-02 18:42 UTC, redknight990 commented on src/Modules.h
> +class GroundStationWindow{
This class I would leave in its own header file, also rename to something more generic, perhaps `UIWindow` or `UIPanel`

2022-02-02 21:01 UTC, AdmiralAki99 commented on src/Modules.h
> +class GroundStationWindow{
I renamed it to UIWindowTemplate, thought it might be self-explanatory and more readable.

2022-02-02 21:14 UTC, AdmiralAki99 commented on src/Modules.h
> +class GroundStationWindow{
I created directory Modules so that we can Include the separated Modules when we want to. I can change it if it complicates stuff.

2022-02-09 00:25 UTC, redknight990 approved these changes
Approved from me!

2022-02-09 00:26 UTC, mattmazzone approved these changes
Looks good to me

2022-02-09 00:26 UTC, merged